# -*- coding: utf-8 -*-
"""Copy of AF3005–Assignment_2_Financial_App_Development_with_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRF3iJj7ZONK4uXOM_t6hv3_ikBIoWro

# **AF3005 – Programming for Finance**  

---

## **📘 Assignment 2: Financial App Development with Streamlit**  

📍 **FAST National University of Computer and Emerging Sciences (FAST-NUCES), Islamabad**  
👨‍🏫 **Instructor:** Dr. Usama Arshad (Assistant Professor, FSM)  
🎓 **Program:** BS Financial Technology (BSFT)  
📅 **Semester:** Spring 2025  
📌 **Sections:** BSFT06A, BSFT06B, BSFT06C  

---

## **🎯 Course Learning Outcomes (CLOs)**
- **CLO3:** Develop financial models and algorithms for decision-making. (PLO 3, PLO 5)
- **CLO4:** Automate financial processes and calculations using Python programming. (PLO 4, PLO 5)
- **CLO5:** Visualize and interpret financial data effectively using Python tools. (PLO 1, PLO 3)


---

# **🟢 Assignment 2: Financial App Development [20 marks]**

---


## **📍 Task Description**
Students will build a **unique, useful, or practical financial web app** using **Streamlit** and deploy it on **Streamlit Share**. The app must be interactive and handle **financial data**, but **no AI integration of anykind is required**. You can use any publically available financial data or use your own.

---

## **📍 Requirements**
### **1️⃣ Creativity & Uniqueness** 🧠 (3 Marks)  
   - The idea must be **unique, practical, or useful** in the financial domain.

### **2️⃣ App Development with Streamlit** 🖥️ (8 Marks)  
   - Use **Streamlit** to create an interactive financial app.
   - The app should have:
     - A **clear purpose** related to finance.
     - **User input options** (sliders, dropdowns, forms, etc.).
     - **Financial data visualization** (graphs, charts, tables).

### **3️⃣ Deployment on Streamlit Share** 🌍 (3 Marks)  
   - The app must be **hosted on Streamlit Cloud** and accessible via a public link.

### **4️⃣ GitHub Repository & Documentation** 📂 (3 Marks)  
   - Upload the **complete project on GitHub**.
   - **README.md file must include:**
     - **Course Name:** AF3005 – Programming for Finance  
     - **Instructor Name:** Dr. Usama Arshad  
     - **App Overview** (What does the app do?)  
     - **Installation Guide** (How to run it locally?)  
     - **Deployment Link** (Streamlit app URL)  
     - **Screenshots or a small video demo**  
     - **GitHub Repository Link**  

### **5️⃣ LinkedIn Post** 🔗 (3 Marks)  
   - Each student must post about their project on **LinkedIn** with:
     - **Project Description**
     - **GitHub Repository Link**
     - **Streamlit App Link**
     - **Course Name & Instructor Name**
     - **A Small Video Showing How the App Works**
   - Tag **Dr. Usama Arshad** and use relevant hashtags:  
     `#FinTech #ProgrammingForFinance #Python #Streamlit #FinanceApps`

---

## **📍 Evaluation Criteria (Total: 20 Marks)**
| Component                     | Marks |
|--------------------------------|-------|
| Creativity & Novelty          | 3     |
| Proper App Functionality      | 8     |
| Deployment on Streamlit       | 3     |
| GitHub Repository & README    | 3     |
| LinkedIn Post with Links & Video | 3     |
| **Total**                     | **20** |

---

## **📍 Ideas for Financial Apps**
Students can choose their own ideas, but here are some suggestions:
- **Budget Tracker** 💰 (Track income & expenses)
- **Stock Market Dashboard** 📈 (Real-time stock data visualization)
- **Cryptocurrency Portfolio Tracker** 🪙
- **Loan Calculator** 💳 (EMI calculation with interactive sliders)
- **Savings Goal Planner** 🎯
- **Investment Portfolio Analyzer** 📊
- **Forex Exchange Rate Tracker** 💹
- **Personal Finance Quiz App** 🧠 (Interactive quizzes on financial literacy)
- **Tax Estimator** 🏦 (Estimate yearly tax based on user input)

---

## **📍 Submission Guidelines**
1. **GitHub Repository:**  
   - Upload all code files, `requirements.txt`, and a proper `README.md`.  
   - Include **Course Name, Instructor Name, App Overview, Deployment Link, and a Demo Video**.  
   - **Share the repository link.**

2. **Streamlit Share Deployment:**  
   - Share the deployed app link.

3. **LinkedIn Post:**  
   - Post about your app on LinkedIn with:
     - **Project Description**
     - **GitHub Link**
     - **Streamlit App Link**
     - **Demo Video**
     - **Instructor Tag & Hashtags**

4. **Submission Form:**  
   - Submit **GitHub link, Streamlit link, and LinkedIn post link** in the designated form.

---
"""

class TaxEstimator:
    def __init__(self, income, deductions=0):
        self.income = income
        self.deductions = deductions
        self.taxable_income = max(0, self.income - self.deductions)

    def calculate_tax(self):
        tax_brackets = [
            (9875, 0.10),
            (40125, 0.12),
            (85525, 0.22),
            (163300, 0.24),
            (207350, 0.32),
            (518400, 0.35),
            (float("inf"), 0.37),
        ]

        tax_owed = 0
        previous_bracket = 0
        for bracket, rate in tax_brackets:
            if self.taxable_income > previous_bracket:
                taxable_at_this_rate = min(self.taxable_income, bracket) - previous_bracket
                tax_owed += taxable_at_this_rate * rate
                previous_bracket = bracket
            else:
                break

        return round(tax_owed, 2)

    def display_estimate(self):
        print(f"Total Income: ${self.income}")
        print(f"Deductions: ${self.deductions}")
        print(f"Taxable Income: ${self.taxable_income}")
        print(f"Estimated Tax Owed: ${self.calculate_tax()}")


if __name__ == "__main__":
    income = float(input("Enter your annual income: "))
    deductions = float(input("Enter your total deductions: "))

    estimator = TaxEstimator(income, deductions)
    estimator.display_estimate()